title: Marcel Hlopko
email: marcel@hlopko.com
description: "Hunting for focus"
url: "http://blog.hlopko.com"
timezone: "Europe/Prague"

author :
  name : Marcel Hlopko
  email : marcel@hlopko.com
  github : hlopko
  twitter : marcelhlopko

markdown: kramdown
redcarpet:
  extensions: ["tables", "no_intra_emphasis", "autolink"]
permalink: pretty

comments :
  provider : disqus
  disqus :
    short_name : mhlopko
